server:
  port: 8888
spring:
  datasource:
    url: jdbc:h2:file:~/ise;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
  h2:
    console:
      enabled: true
hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
      address: /fhir
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jpa
      server-version: 1.0.0
      implementation-description: Spring Boot Jpa Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    jpa:
      scheduling-disabled: false
      subscription-matching-enabled: true
    logging:
      logger-name: fhir.access
      message-format: "[${idOrResourceName}.${operationType}] ${requestBodyFhir}"
      log-exceptions: true
      error-message-format: "[ERROR - ${idOrResourceName}.${operationType}] ${exceptionMessage}"
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: env,mappings,beans,conditions
